Phase02 refactoring
Star-Academy/Summer1403-SE-Team02 pull request #4
Opened 2024-07-27 12:04 UTC by msmahdinejad

2024-07-28 05:14 UTC, AliSK81 requested changes
قرار شد برا هر فاز فولدر جدا بزنیم
کدهای فاز 2 رو توی این برنچ تغییر ندین

2024-07-28 08:26 UTC, AliSK81 requested changes

2024-07-28 08:26 UTC, AliSK81 commented on phase03/Program.cs
> +        catch (Exception ex)
لینک های چنل دیسکورد رو چک کنیم
برای مدیریت خطا Best practice چیه؟

2024-07-28 08:26 UTC, AliSK81 commented on phase03/Program.cs
> +                    Console.WriteLine("Key not found!");
move messages to resource file

2024-07-28 08:26 UTC, AliSK81 commented on phase03/Program.cs
> +    public static void Main()
چرا این تابع داره کلی کار میکنه؟

2024-07-28 08:26 UTC, AliSK81 commented on phase03/abstraction/IFolderReader.cs
> +    IEnumerable<ISearchable> RaedFolder(string path);
typo: Read

2024-07-28 08:26 UTC, AliSK81 commented on phase03/abstraction/IFolderReader.cs
> +    IEnumerable<ISearchable> RaedFolder(string path);
چرا خروجی این متد باید ISearchable باشه؟ یعنی هم از فایل میخونه هم به یه چیز searchable تبدیل میکنه؟ single responsibility violated

2024-07-28 08:26 UTC, AliSK81 commented on phase03/abstraction/IInvertedindex.cs
> +}
چرا این اینترفیس هیچ تابعی برای retrive کردن داده از inverted index نداره؟ 
احتمالا توی پیاده سازی encapsulation رعایت نشده

2024-07-28 08:26 UTC, AliSK81 commented on phase03/abstraction/IProcessor.cs
> +    void Build();
چرا processor باید چیزی رو بیلد کنه؟ اصلا چیو build میکنه؟

2024-07-28 08:26 UTC, AliSK81 commented on phase03/abstraction/IProcessor.cs
> +    HashSet<ISearchable> Search(Query query);
چیزی که ISearchable هست از اسمش انتظار میره روش سرچ انجام بشه
نه اینکه نتیجه سرچ باشه

2024-07-28 08:26 UTC, AliSK81 commented on phase03/abstraction/IQuery.cs
> +}
IQuery یا IQueryBuilder?

2024-07-28 08:26 UTC, AliSK81 commented on phase03/abstraction/IQuery.cs
> +}
منطق build کردن بره توی بیلدر

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Document/DocumentReader.cs
> +public class DocumentReader : IFolderReader
داکیومنت مگه نوعی فولدره؟

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Document/DocumentReader.cs
> +public class DocumentReader : IFolderReader
نام گذاری ها بهتر بشه

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Document/DocumentReader.cs
> +    public static DocumentReader Instance => _DocumentReader ??= new DocumentReader();
سینگلتون اینجوری خوب نیست

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Document/DocumentReader.cs
> +    private string RaedData(string path)
typo

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Document/DocumentReader.cs
> +            throw new Exception("Path not found!");
move to .resx

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/ExtensionMethods/StringExtesion.cs
> +        string[] wordList = text.Split(new[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
define class readonly const properties

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/ExtensionMethods/StringExtesion.cs
> +public static class StringExtension
اینجوری هرجا استرینگ داشته باشیم بعدش نقطه بزنیم این اکستنشن هارو میبینیم
با این حساب منطقیه برای تایپ استرینگ اکستنشن متد بنویسیم؟

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Factory/FolderReaderFactory.cs
> +            {"Document", DocumentReader.Instance}
هیچ جایی از کد استرینگ هاردکد نکنیم (چرا؟)
میشه const property تعریف کرد اما چون جاهای مختلف کد استفاده میشه ممکنه اشتباه تایپی و .. بوجود بیاد
میتونیم Enum استفاده کنیم

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Factory/FolderReaderFactory.cs
> +            throw new Exception("Class not found!");
bad practice

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Factory/FolderReaderFactory.cs
> +            throw new Exception("Class not found!");
define custom exception and handle properly

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Factory/SearchStrategyFactory.cs
> +    }
مشابه بالا

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Processor.cs
> +public class Processor : IProcessor
یکم برای نامگذاری ها دامنه قائل بشیم
مثلا محدوده ما پردازش فایل هست بگیم FileProcessor

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Processor.cs
> +        _invertedIndex = new InvertedIndexController();
Dependency inversion violated

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Processor.cs
> +public class Processor : IProcessor
single responsibility violated (search and build)

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Search/IntersectResultList.cs
> +public class IntersectResultList : ISearchResultList
از اسم کلاس مشخص نیست چه کاری میکنه
کانونشن نامگذاری رعایت نشده

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Search/IntersectResultList.cs
> +        if (keyList.Count >= 1)
invert if

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Search/SignedQuery.cs
> +public class SignedQuery : IQuery
توی این کلاس open close رعایت نشده

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Search/SignedQuery.cs
> +public class SignedQuery : IQuery
چرا؟

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Search/SignedSearchStrategy.cs
> +        }
open close violated

2024-07-28 08:26 UTC, AliSK81 commented on phase03/business/Search/SignedSearchStrategy.cs
> +        }
میتونیم بهتر بدون if پیاده سازی کنیم که راه تغییر رو ببندیم؟

2024-07-29 06:53 UTC, tahadavari approved these changes

2024-07-29 07:02 UTC, AliSK81 requested changes
لطفا
1. نامگذاری اینترفیس ها و متدها دقیق تر باشه جوری که از اسمشون بفهمیم دقیقا چیکار میکنه یا Summary ّنویسیم
2. خیلی جاها میتونیم منطق رو بشکنیم به متدهای پرایوت که کد خوانا تر و کوتاه تر بشه 
3. کلاس های استراتژی که دارین معلوم نیست کارشون چیه و انگار خیلی کارا دارن میکنن
4. اکسپشن های سیستمی رو نیاز نیست هندل کنیم اما اکسپشن های کاستوم رو باید بکنیم

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Document/DocumentFolderReader.cs
> +    private const string _FolderName = "Document";
remove underline

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Document/DocumentFolderReader.cs
> +            throw new InvalidFolderPath();
set inner exception to keep stacktrace

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Document/DocumentFolderReader.cs
> +            throw new InvalidFolderPath();
FileNotFoundException must be inner exception of InvalidFolderPath

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Document/Formater/TextEditor.cs
> +        string[] wordList = text.Split(new[] { ' ', '\t', '\n', '\r' }, StringSplitOptions.RemoveEmptyEntries);
define static delimiters

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Document/IDataFolderReader.cs
> +    string GetClassName();
can be converted to property

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Document/ISearchable.cs
> +    string GetValue();
can be converted to property

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Factory/SearchFactory/SearchStrategyFactory.cs
> +    private List<ISearchStrategy> _searchStrategyList { get; set; }
readonly

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Initialize/Initializer.cs
> +    public void Build(string className, string folderPath, string searchType, IDataFolderReaderFactory inputDataFolderReaderFactory, IInvertedIndex inputInvertedIndex, ISearchStrategyFactory inputSea
too many params

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Initialize/Initializer.cs
> +public class Initializer : IInitializer
FolanBisarInitializer

2024-07-29 07:02 UTC, AliSK81 commented on phase03/Program.cs
> +    private const string _invalidKeyMessage = "Key Not Found!";
PascalCase

2024-07-29 07:02 UTC, AliSK81 commented on phase03/QueryManager/WordFinder/PositiveWordFinder.cs
> +            .Where(word => word[0] == '+')
make '+' private const property

2024-07-29 07:02 UTC, AliSK81 commented on phase03/SearchManager/ResultList/IntersectResultListMaker.cs
> +                    });
long line
extract method

2024-07-29 07:02 UTC, AliSK81 commented on phase03/SearchManager/ResultList/UnionResultListMaker.cs
> +        if (keyList.Count >= 1)
invert if

2024-07-29 07:02 UTC, AliSK81 commented on phase03/SearchManager/SignedSearchStrategy.cs
> +    private const string _searchStrategyName = "SignedSearch";
define StrategyName enum

2024-07-29 12:31 UTC, AliSK81 approved these changes

2024-07-29 14:20 UTC, merged